# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: social-y

test:
  <<: *default
  database: social-y

production:
  <<: *default
  database: social-y
  username: postgres
  password: <%= ENV['postgres'] %>
